version: '3.3'

services:

  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "uvicorn", "main:app", "--host=0.0.0.0", "--port=8888"]
    restart: unless-stopped
    ports:
      - '8888:8888'
    logging:
      driver: 'local'
      options:
        max-size: '10m'
