version: '3.3'

services:

  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: [
      "poetry", "run", "uvicorn", "main:app",
      "--host=0.0.0.0",
      "--port=443",
      "--ssl-keyfile=/certs/selfsigned.key",
      "--ssl-certfile=/certs/selfsigned.crt"
    ]
    restart: unless-stopped
    ports:
      - '8888:8888'
      - '433:433'
    volumes:
      - ./certs:/certs
    logging:
      driver: 'local'
      options:
        max-size: '10m'
